### ISSUE TITLE
Feather board does not always restart after deepsleep

### ISSUE THREAD

**Issue by tomjorquera** [tomjorquera/pico-micropython-lowpower-workaround#1]
@industrialinternet reported [on the micropython repo](https://github.com/micropython/micropython/issues/7035#issuecomment-834296351) that their feather board did not always restart when running the ` lowpower_example.py` script.

Sadly I don't have this boards (yet?) so I cannot try to reproduce the issue at the moment.

**Comment by industrialinternet** [comment]
Hi I've tested on tiny2040 with an external wake timer from Domant state.
If serial console is still connected there are issues.
But when running just usb power & no console connection works fine.

I tested the Feather with same external wake timer on usb power from battery and it still doesn't come back from Dormant.

**Comment by tomjorquera** [comment]
I think the issue is solved with the merge of #11 

If someone can still reproduce the issue with the latest version, feel free to chime in.
