### ISSUE TITLE
validation rejecting Pin28

### ISSUE THREAD

**Issue by davidmcnabnz** [tomjorquera/pico-micropython-lowpower-workaround#13]
On my Pi Pico and Pico W devices, pins range from GP0 to GP28.

However, lowpower.py's validation only accepts up to 27.

Recommending this limit be changed to 28 to accommodate use of GP28  for dormant wake-up.

**Comment by tomjorquera** [comment]
Off by one error strikes again... Fixed it, thanks for the report !
