### ISSUE TITLE
TypeError: unsupported types for __truediv__: 'Pin', 'int'

### ISSUE THREAD

**Issue by thbeh** [tomjorquera/pico-micropython-lowpower-workaround#3]
Hi, I am testing your lowpower/dormant module but getting the following error. My environment is :- 
**MicroPython v1.15 on 2021-04-18; Raspberry Pi Pico with RP2040**

Please advise. Did I miss anything?

_Traceback (most recent call last):
  File "\<stdin\>", line 26, in <module>
  File "lowpower.py", line 79, in dormant_until_pin
  File "lowpower.py", line 60, in dormant_until_pins
  File "lowpower.py", line 42, in gpio_acknowledge_irq
TypeError: unsupported types for \_\_truediv\_\_: 'Pin', 'int'_

**Comment by tomjorquera** [comment]
Posting your exact code would help, but looking at the stacktrace you posted and at the [relevant line](https://github.com/tomjorquera/pico-micropython-lowpower-workaround/blob/298ada1832d2af3d52a10ef1be9c921549a8b30c/lowpower.py#L42), I would guess that you tried to call `lowpower.dormant_until_pin` with a Pin object as argument.

`dormant_until_pin` (and the other functions) don't take a Pin object, but the pin number itself directly.

So your code should look something like:

```
DORMANT_PIN = 15
...
lowpower.dormant_until_pin(DORMANT_PIN)
```

As an aside, I guess it would be nice if the code worked with both pin numbers and Pin objects. Maybe I will take a shot at it if I find time.

**Comment by thbeh** [comment]
How did I miss that. Thank you very much.
