### ISSUE TITLE
Hardware Requirements

### ISSUE THREAD

**Issue by tjonesrobotics** [tomjorquera/pico-micropython-lowpower-workaround#4]
I've run the code, and I'm able to get into the dormant mode. However, my pico doesn't wake up on the GPIO signal.

I believe this is because I'm not using an external oscillator, which seems to be required with the C libraries for going dormant. Is an external oscillator required with your library? And if it is, could that be added to the Read_Me?

**Comment by tomjorquera** [comment]
Hi @tjonesrobotics

I tested my workaround on two of my "vanilla" pico, and it worked without an external oscillator. However, like I said in the readme, this is really hacked together , so you may definitely have hit a snag.

That says, a few things:
- Are you using a base pico, or one of the variants? I only tested on the base model, and some people reported the lib not working for them on variants
- Quadruple check your connections. Seriously. At some point I was hitting a lot of issues with my pico not waking up. When improving the cabling, my issues suddenly disappeared. Not saying it will solve your issues, but definitely something to consider
- How are you powering your pico? I did not check thoroughly, but I suspect there may be difference between powering with usb from a computer and with an external alim. Also one user mentioned the lib working on one of the variants only when disabling the serial console

**Comment by tjonesrobotics** [comment]
I am using the base pico, no variants. The connections are all good, too. 

I had been powering it from USB from my laptop. At your suggestion, I switched the power to an external battery, and the pins through the V_SYS, and the GPIO signal started waking up the processor. It's interesting that the power source would cause a difference. It may be something related to the detection of which power source is being used, since GPIO24 can provide that data.

For my application, I put the dormant_until_pins() command inside an "if" statement to check whether it's being powered by USB or battery. Thanks!
