### ISSUE TITLE
Noob needs help

### ISSUE THREAD

**Issue by oxicottin** [tomjorquera/pico-micropython-lowpower-workaround#7]
Hello, I need my entire Tiny2040 to go dormant after a while loop and wake by button press lets say GPIO-5.  I know how to upload the library you posted but I don't understand the example on how to incorporate it into mine? If I'm right it seems you make selected "Pins" dormmate and I need all my pins dormmate and to wake on the button press.

**Comment by tomjorquera** [comment]
Hey @oxicottin ! Sorry for the late reply.

No it's not only selected pins that go dormant, but the whole pico. The pins referenced in the code are the pins that can be used to *wake up* the pico (but looking at my rather discutable choice of variable names examples, I can get the confusion)

Hope that clarifies things up!
